[tools]
cheat = "4.4.0"
delta = "0.16.5"
duf = "0.8.1"
dust = "0.8.6"
fd = "8.7.0"
fzf = "0.42.0"
jq = "1.7"
nodejs = "18.17.1"
ripgrep = "13.0.0"
starship = "1.16.0"
zoxide = "0.9.2"

[plugins]
cheat = "https://github.com/jmoratilla/asdf-cheat-plugin"
delta = "https://github.com/andweeb/asdf-delta"
dust = "https://github.com/looztra/asdf-dust"
duf = "https://github.com/NeoHsu/asdf-duf.git"
fd = "https://gitlab.com/wt0f/asdf-fd"
fzf = "https://github.com/kompiro/asdf-fzf"
jq = "https://github.com/lsanwick/asdf-jq"
nodejs = "https://github.com/rtx-plugins/rtx-nodejs"
ripgrep = "https://gitlab.com/wt0f/asdf-ripgrep"
starship = "https://github.com/grimoh/asdf-starship"
zoxide = "https://github.com/nyrst/asdf-zoxide"

# TODO:
# - https://gitlab.com/wt0f/asdf-bat.git - add apple arm support
# - https://github.com/ogham/dog - create
# - https://github.com/dalance/procs - create
# - https://github.com/nicolargo/glances - create
# - https://github.com/tldr-pages/tldr - create
# - https://github.com/lsd-rs/lsd - create
# - https://github.com/eza-community/eza - create
