[tools]
cheat = "4.4.0"
delta = "0.16.5"
duf = "0.8.1"
dust = "0.8.6"
fd = "8.7.0"
fzf = "0.42.0"
jq = "1.7"
lsd = "1.0.0"
nodejs = "18.17.1"
ripgrep = "13.0.0"
starship = "1.16.0"
zoxide = "0.9.2"

[plugins]
cheat = "https://github.com/jmoratilla/asdf-cheat-plugin"
delta = "https://github.com/andweeb/asdf-delta"
duf = "https://github.com/NeoHsu/asdf-duf.git"
dust = "https://github.com/looztra/asdf-dust"
fd = "https://gitlab.com/wt0f/asdf-fd"
fzf = "https://github.com/kompiro/asdf-fzf"
jq = "https://github.com/lsanwick/asdf-jq"
lsd = "https://github.com/ossareh/asdf-lsd"
nodejs = "https://github.com/rtx-plugins/rtx-nodejs"
ripgrep = "https://gitlab.com/wt0f/asdf-ripgrep"
starship = "https://github.com/grimoh/asdf-starship"
zoxide = "https://github.com/nyrst/asdf-zoxide"

# TODO:
#
# - https://gitlab.com/wt0f/asdf-bat.git
#   - add apple arm support; not straight forwarded - need to wait for github to support arm runners
#   - could the tmux asdf be an example of how to do this?
# - https://github.com/ogham/dog
#   - create asdf package; add apple arm support
# - https://github.com/dalance/procs
#   - create asdf package; add apple arm support
# - https://github.com/nicolargo/glances
#   - create asdf package; no build at all (look at tmux?)
# - https://github.com/eza-community/eza
#   - create asdf package; add apple arm support
