[tools]

# languages + runtimes
rust = "latest"
go = "latest"
nodejs = "latest"
python = "latest"
zig = "latest"

# github releases

"ubi:BurntSushi/ripgrep" = { version = "latest", exe = "rg" }
"ubi:ajeetdsouza/zoxide" = "latest"
"ubi:cli/cli" = { version = "latest", exe = "gh" }
"ubi:junegunn/fzf" = "latest"
"ubi:starship/starship" = "latest"
"ubi:twpayne/chezmoi" = "latest"
"ubi:dandavison/delta" = "latest"
"ubi:muesli/duf" = "latest"
"ubi:sharkdp/fd" = "latest"
"ubi:jqlang/jq" = "latest"
"ubi:koalaman/shellcheck" = "latest"
"ubi:sharkdp/bat" = "latest"
"ubi:ogham/dog" = "latest"

# cargo releases

"cargo:du-dust" = "latest"
"cargo:eza" = "latest"
"cargo:zellij" = "latest"
"cargo:procs" = "latest"
