[tools]
cheat = "4.4.0"
chezmoi = "2.47.0"
delta = "0.16.5"
duf = "0.8.1"
dust = "0.9.0"
fd = "9.0.0"
fzf = "0.46.1"
go = "1.21"
jq = "1.7.1"
lsd = "1.0.0"
nodejs = "20.11.1"
python = "3.11.8"
ripgrep = "14.1.0"
shellcheck = "0.9.0"
shfmt = "3.8.0"
starship = "1.18.2"
zoxide = "0.9.4"
tmux = "3.3a"

# TODO:
#
# - https://gitlab.com/wt0f/asdf-bat.git
#   - add apple arm support; not straight forwarded - need to wait for github to support arm runners
#   - could the tmux asdf be an example of how to do this?
# - https://github.com/ogham/dog
#   - create asdf package; add apple arm support
# - https://github.com/dalance/procs
#   - create asdf package; add apple arm support
# - https://github.com/nicolargo/glances
#   - create asdf package; no build at all (look at tmux?)
# - https://github.com/eza-community/eza
#   - create asdf package; add apple arm support
