#!/bin/bash

#####
# After much digging around I found that this is the right place to start apps
# I don't know how universally true that statement is; there seems to be something
# askew between xmonad and gdm. The fedora xmonad /usr/share/xsession/xmonad.session
# file executes xmonad-start, looking into xmonad-start it looks to call this file.
#
# Apparently DM's that are not XDM seem to not want to call .xsession unless
# their /usr/share/xession entry has the correct incantations

# set background color gray13 == "#333333"
xsetroot -solid gray13

# start tray app (TODO: replace with stalonetray
[ -x /usr/bin/trayer ] && trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 15 --height 20 --transparent true --alpha 255 &

# network monitor app, --sm-disable prevents multiple copies starting
[ -x /usr/bin/nm-applet ] && nm-applet --sm-disable &
